### DISCUSSION TITLE
v1.0.5

### DISCUSSION THREAD

**Discussion by gssariev** [gssariev/overr-syncerr#14] [Announcements]
# Changes
### Subtitle Translations
Added support for subtitles translation using OpenAI GPT. The feature is option and requires that you have an OpenAI API Key. 

The docker-compose has been updated with the following:

   ```
  ###### GPT TRANSLATION - IGNORE IF NOT USING
      ENABLE_GPT: false
      MODEL_GPT: "gpt-4o" # Use your preffered model
      OPEN_AI_API_KEY: "YOU_OPENAI_API_KEY"
      MAX_REQUEST_BYTES: 2000 # The amount of information send with each requests.
      MAX_TOKENS: 4000 # Max tokens for the chosel GPT model
      CHUNK_OVERLAP: 2  # Overlap of one subtitle line between chunks
      REQUEST_DELAY: 2 # Delay between server requests in seconds
      
      MOVIE_PATH_MAPPING: M:\Movies # Map to match the Bazarr path to your movies
      TV_PATH_MAPPING: M:\TV # Map to match the Bazarr path to your series 
      
    volumes:
      - M:\Movies:/mnt/movies
      - M:\TV:/mnt/tv
     ####### END OF GPT TRANSLATION
```

You can trigger subtitles translation with GPT the same way as you normally would: translate 'language code to 'language code'.

### Plex Watchlist (add user-label)
Auto media labeling will not periodically monitor user watchlist and add user label to that media in Plex.

<hr /><em>This discussion was created from the release <a href='https://github.com/gssariev/overr-syncerr/releases/tag/v1.0.5'>v1.0.5</a>.</em>
