### ISSUE TITLE
Can't catch subtitle path

### ISSUE THREAD

**Issue by JohnCytron** [gssariev/overr-syncerr#24]
Hello,

I have an issue to catch the subtitle path even if it's present to the bazarr answer. Any idea ?

docker compose setup:
```yaml
  overr-syncerr: #  Webhook handler for subtitle management (hhttps://github.com/gssariev/overr-syncerr)
    image: gsariev/overr-syncerr:latest
    container_name: overr-syncerr
    restart: unless-stopped
    env_file:
      - "./env/common.env"
      - "./secret/overr-syncerr.env" # BAZARR_API_KEY RADARR_API_KEY SONARR_API_KEY OVERSEERR_API_KEY PLEX_TOKEN SERVER_CLIENTID
    environment:
      #BAZARR CONFIG
      BAZARR_URL: "http://bazarr:6767/api"
      #RADARR CONFIG
      RADARR_URL: "http://radarr:7878/api/v3"
      #SONARR CONFIG
      SONARR_URL: "http://sonarr:8989/api/v3"
      #OVERSEERR or JELLYSEERR CONFIG
      OVERSEERR_URL: "http://jellyseerr:5055/api/v1"
      #PLEX CONFIG
      PLEX_HOST: "http://plex:32400"
      # ANIME_LIBRARY_NAME: "YOUR_ANIME_LIBRARY_NAME"
      MOVIES_LIBRARY_NAME: "Films"
      SERIES_LIBRARY_NAME: "Séries"
      #ADDITIONAL OPTIONS CONFIG
      ENABLE_KOMETA: "false"
      ENABLE_MEDIA_AVAILABLE_HANDLING: "false" #Enable if you want to use auto-label, kometa overlays or audio preference
      ENABLE_AUDIO_PREF: "true" #Enable if you want to use user specific audio preference
      MONITOR_REQUESTS: "false" #Enable if you want to add label or set audio to media that's partially available
      CHECK_REQUEST_INTERVAL: 900 #Set the desired interval for monitor request to execute (in seconds)
      PORT: 8089 #Webhook port
      LANGUAGE_MAP: '{"en":"English", "eng":"English", "english":"English", "fr":"French", "fra":"French", "french":"French"}' #Replace with your own keywords
      SYNC_KEYWORDS: '["sync", "out of sync", "messed up", "synchronization", "synchronisation", "synchro", "désynchronisé", "synchronisé"]' #Replace with your own keywords
      ADD_LABEL_KEYWORDS: '["add to library", "ajouter à ma bibliothèque"]' #Replace with your own keywords
    volumes:
      - "/docker/app/overr-syncerr/config/:/mnt/usr/"
    networks:
      - proxy-net
 ```

overr-syncerr log:
```
[INF] Received payload: {"notification_type":"ISSUE_CREATED","event":"New Subtitle Issue Reported","subject":"Rollerball (1975)","message":"sync","image":"https://image.tmdb.org/t/p/w600_and_h900_bestv2/cmcipEfexlhVLYQXqeSWp1YcsPY.jpg","media":{"media_type":"movie","tmdbId":"11484","tvdbId":"","status":"AVAILABLE","status4k":"UNKNOWN"},"request":null,"issue":{"issue_id":"4","issue_type":"SUBTITLES","issue_status":"OPEN","reportedBy_email":"REDACTED","reportedBy_username":"REDACTED","reportedBy_avatar":"https://plex.tv/users/REDACTED/avatar?c= REDACTED","reportedBy_settings_discordId":"REDACTED","reportedBy_settings_telegramChatId":""},"comment":null,"extra":[]}
[INF] Payload enqueued successfully.
[INF] Processing payload: {"notification_type":"ISSUE_CREATED","event":"New Subtitle Issue Reported","subject":"Rollerball (1975)","message":"sync","image":"https://image.tmdb.org/t/p/w600_and_h900_bestv2/cmcipEfexlhVLYQXqeSWp1YcsPY.jpg","media":{"media_type":"movie","tmdbId":"11484","tvdbId":"","status":"AVAILABLE","status4k":"UNKNOWN"},"request":null,"issue":{"issue_id":"4","issue_type":"SUBTITLES","issue_status":"OPEN","reportedBy_email":"REDACTED","reportedBy_username":"REDACTED","reportedBy_avatar":"https://plex.tv/users/REDACTED/avatar?c= REDACTED","reportedBy_settings_discordId":"REDACTED","reportedBy_settings_telegramChatId":""},"comment":null,"extra":[]}
[INF] Subtitle issue detected
[WRN] User not found, using default locale.
[INF] Matching pattern: adjust\s+by\s+(-?\d+)\s*(s|ms|m|min)? against message: 'sync'
[WRN] Pattern did not match.
[INF] Using bazarrUrl: http://bazarr:6767/api
[INF] Fetching movie details from Radarr for tmdbId: 11484
[SUC] Movie ID: 675, Radarr ID: 675
[INF] Mapped Language Name: 
[INF] Subtitle Path: 
[ERR] Subtitles are either embedded or missing - cannot sync.
[SUC] Posted comment to Overseerr issue 4
[SUC] Marking issue as resolved.
[SUC] 
[SUC] All payloads processed.
``` 

Bazarr answer `GET /api/movies?start=0&length=-1&radarrid%5B%5D=675&apikey=REDACTED` :
```json
{
  "data": [
    {
      "alternativeTitles": [
        "Rollerball, \u00bfun futuro pr\u00f3ximo?"
      ],
      "audio_language": [
        {
          "name": "English",
          "code2": "en",
          "code3": "eng"
        }
      ],
      "fanart": "/images/movies/MediaCover/675/fanart.jpg?lastWrite=638744552050276198",
      "imdbId": "tt0073631",
      "missing_subtitles": [],
      "monitored": false,
      "overview": "En l\u2019an 2018, les cadres dirigeants se sont substitu\u00e9s aux hommes politiques, et les Etats ont \u00e9t\u00e9 remplac\u00e9s par six d\u00e9partements mondiaux : \u00c9nergie bas\u00e9e \u00e0 Houston, Luxe, Alimentation, Logement, Communications et Transports. Gr\u00e2ce \u00e0 cette organisation, tous les hommes jouissent d\u2019un confort de vie in\u00e9gal\u00e9. Mais une soci\u00e9t\u00e9 en paix a besoin de purger les pulsions violentes de ses membres. C\u2019est dans ce but qu\u2019a \u00e9t\u00e9 cr\u00e9\u00e9 le Rollerball, un sport tr\u00e8s violent et l\u00e9tal ne permettant pas l'\u00e9mergence de vedettes individuelles, \u00e0 la fois m\u00e9lange de hockey, de boxe, de football am\u00e9ricain. Jonathan E. brise ce tabou en survivant \u00e0 de nombreux matches disput\u00e9s sans r\u00e8gles, mettant ainsi \u00e0 mal la philosophie m\u00eame du Rollerball et de cette soci\u00e9t\u00e9 du futur : \u00ab Le jeu est plus grand que le joueur \u00bb.",
      "path": "/data/media/film/archive/Rollerball (1975) [imdb-tt0073631]/Rollerball.1975 {imdb-tt0073631}.mkv",
      "poster": "/images/movies/MediaCover/675/poster-500.jpg?lastWrite=638590508735167937",
      "profileId": 1,
      "radarrId": 675,
      "sceneName": "Rollerball.1975",
      "subtitles": [
        {
          "name": "French",
          "code2": "fr",
          "code3": "fra",
          "path": "/data/media/film/archive/Rollerball (1975) [imdb-tt0073631]/Rollerball.1975 {imdb-tt0073631}.fr.srt",
          "forced": false,
          "hi": false,
          "file_size": 74539
        }
      ],
      "tags": [
        "archive"
      ],
      "title": "Rollerball",
      "year": "1975"
    }
  ],
  "total": 454
}
```
