### ISSUE TITLE
Over-Syncerr docker issues with Apple Silicon on macOS 15.4.1

### ISSUE THREAD

**Issue by PaRkThEcAr** [gssariev/overr-syncerr#28]
Afternoon! so i have had this running as part of a larger stack for a while now, but after updating to macOS 15.4.1 on an Apple Silicon server, i get this error on the compose file
```
╰─ docker compose -f ./oversyncer-docker-compose.yml up -d                   ─╯
[+] Running 0/1
 ⠸ overr-syncerr Pulling                                                   1.3s 
no matching manifest for linux/arm64/v8 in the manifest list entries
```

here is my docker-compose file:
```
---
services:
  overr-syncerr:
    image: gsariev/overr-syncerr:latest
    container_name: overr-syncerr
    ports:
      - "8089:8089"
    environment:
      #BAZARR CONFIG
      BAZARR_API_KEY: "$REDACTED""
      BAZARR_URL: "http://192.168.1.68:6767/api"

      #RADARR CONFIG
      RADARR_API_KEY: "$REDACTED""
      RADARR_URL: "http://192.168.1.68:7878/api/v3"

      #SONARR CONFIG
      SONARR_API_KEY: "$REDACTED""
      SONARR_URL: "http://192.168.1.68:8989/api/v3"

      #OVERSEERR or JELLYSEERR CONFIG
      OVERSEERR_API_KEY: "$REDACTED""
      OVERSEERR_URL: "http://192.168.1.68:5055/api/v1"

      #PLEX CONFIG
      PLEX_TOKEN: "$REDACTED""
      PLEX_HOST: "http://192.168.1.68:32400"
      ANIME_LIBRARY_NAME: "TV Shows"
      MOVIES_LIBRARY_NAME: "Movies"
      SERIES_LIBRARY_NAME: "TV Shows"
      SERVER_CLIENTID: "$REDACTED""

      #GPT CONFIG
      #Replace the gpt model with the one you wish.
      #Bytesize, tokens, chuncks and delays can be left as is.
      ENABLE_GPT: "false"
      MODEL_GPT: "gpt-4o"
      OPEN_AI_API_KEY: "$REDACTED"
      MAX_REQUEST_BYTES: 2000
      MAX_TOKENS: 4000
      CHUNK_OVERLAP: 2
      REQUEST_DELAY: 2

      #Provide the locations Bazarr stores subtitles to use with GPT; else, leave empty
      MOVIE_PATH_MAPPING: "M:\\Movies\\1080p" #Bazarr subtitles path for GPT translation
      TV_PATH_MAPPING: "M:\\TV\\1080p" #Bazarr subtitles path for GPT translation

      #ADDITONAL OPTIONS CONFIG
      ENABLE_KOMETA: "true"
      KOMETA_CONFIG_PATH: /Users/parkthecar/DockerStuff/Kometa
      ENABLE_MEDIA_AVAILABLE_HANDLING: "true" #Enable if you want to use auto-label, kometa overlays or audio preference
      ENABLE_AUDIO_PREF: "true" #Enable if you want to use user specific audio preference
      MONITOR_REQUESTS: "false" #Enable if you want to add label or set audio to media that's partially available
      CHECK_REQUEST_INTERVAL: 10 #Set the desired interval for monitor request to execute (in seconds)
      PORT: 8089 #Webhook port
      LANGUAGE_MAP: "{\"en\":\"English\",\"english\":\"English\",\"eng\":\"English\"}" #Replace with your own keywords
      SYNC_KEYWORDS: "[\"sync\", \"out of sync\", \"messed up\", \"synchronization\"]" #Replace with your own keywords
      ADD_LABEL_KEYWORDS: "[\"add to library\"]" #Replace with your own keywords

    volumes:
      - /Volumes/MegaDrive/MovieLiberation:/Qbittorrent/Downloads
      - /Volumes/MegaDrive/Plex/TV:/Volumes/Plex/TV
      - /Volumes/MegaDrive/Plex/Movies/Overseer:/Volumes/Plex/Movies/Overseer
      - /Volumes/MegaDrive/Plex/Movies/4K:/Volumes/Plex/Movies/4K
      - /Volumes/MegaDrive/Plex/Movies/HD:/Volumes/Plex/Movies/HD
      - /Volumes/MegaDrive/Plex/Movies/SD:/Volumes/Plex/Movies/SD
      - /Users/parkthecar/DockerStuff/MovieLiberation/bazarr/data:/config
      - /Volumes/MegaDrive/MovieLiberation:/downloads
      - /Users/parkthecar/DockerStuff/MovieLiberation/Overr-syncerr:/mnt/usr #Storing user tokens and prefered audio
      - /var/run/docker.sock:/var/run/docker.sock #To trigger Kometa container
    restart: unless-stopped
```
