### ISSUE TITLE
Error Plex Hostname could not be parsed

### ISSUE THREAD

**Issue by hvmzx** [gssariev/overr-syncerr#29]
Hi, I tried setting up overr-syncerr and i got this in the logs :

```2025-04-22T06:44:16.817059925Z [WRN] Fetching Plex user tokens and generating preferences is DISABLED.
2025-04-22T06:44:16.829671299Z [SUC] Language map parsed successfully
2025-04-22T06:44:16.830159457Z [SUC] Sync keywords parsed successfully
2025-04-22T06:44:16.867554797Z [ERR] Error fetching Plex library sections: Invalid URI: The hostname could not be parsed.
2025-04-22T06:44:16.870026951Z [SUC] Movies Section IDs: 
2025-04-22T06:44:16.870266774Z [SUC] Series Section IDs: 
2025-04-22T06:44:16.870540705Z [SUC] Anime Section IDs: 
2025-04-22T06:44:16.871070552Z [WRN] Request monitoring is not enabled. Skipping Overseerr request monitor.
2025-04-22T06:44:16.871501032Z [INF] GPT is not used for subtitle translation.
2025-04-22T06:44:16.871768477Z [WRN] Kometa is DISABLED.
2025-04-22T06:44:16.872126997Z [WRN] Audio preference is DISABLED.
2025-04-22T06:44:16.884442571Z [INF] Listening for webhooks on http://localhost:8089/```

and the compose config :

```      #PLEX CONFIG
      - PLEX_TOKEN=$PLEX_TOKEN
      - PLEX_HOST="http://172.18.0.3:32400"
      #ANIME_LIBRARY_NAME: "YOUR_ANIME_LIBRARY_NAME"
      - MOVIES_LIBRARY_NAME="Shows"
      - SERIES_LIBRARY_NAME="Movies"
      - SERVER_CLIENTID=$PLEX_SERVER_CLIENTID```

For the PLEX_HOST, I tried the docker local ip, but also the local ip of my network (192.168.1.X:32400) and the container name (plex:32400) but neither worked.

Any idea how i could make it work ?

**Comment by gssariev** [comment]
I'd recommend checking:

- Plex token - are you using a valid token?
- Do you have the OS container running on a sub-network or a different network than Plex?

In my setup, I use the local ip of the machine that's running Plex and both of them are on the same network.

**Comment by hvmzx** [comment]
Yeah the token is valid and just got it from the XML url
I run everything on  docker compose, in 1 network

**Comment by gssariev** [comment]
@hvmzx @zmweske 

Could you share your full docker-compose files with me (redacting API keys & Token, of course)

As far as the error you're getting @zmweske , it's an oversight on my part. I'll notify once I've updated the develop container with the fix, but do be aware that this will limit you to only **managing subtitles for translation and synchronization** and features like labels, audio and subtitle preferences won't work as they require Plex to be configured.

**Comment by zmweske** [comment]
```yaml
    environment:
      PORT: 8089
      BAZARR_URL: "http://bazarr:6767/api"
      BAZARR_API_KEY: "key"
      RADARR_URL: "http://radarr:7878/api/v3"
      RADARR_API_KEY: "key"
      SONARR_URL: "http://sonarr:8989/api/v3"
      SONARR_API_KEY: "key"
      OVERSEERR_URL: "http://jellyseerr:5055/api/v1"
      OVERSEERR_API_KEY: "key"
      ENABLE_MEDIA_AVAILABLE_HANDLING: "false" #Enable if you want to use auto-label, kometa overlays or audio preference
      ENABLE_AUDIO_PREF: "false" #Enable if you want to use user specific audio preference
      ENABLE_GPT: "false"
      ENABLE_KOMETA: "false"
      MONITOR_REQUESTS: "false" #Enable if you want to add label or set audio to media that's partially available 
      ADD_LABEL_KEYWORDS: '[]'
      CHECK_REQUEST_INTERVAL: 300 #Set the desired interval for monitor request to execute (in seconds)
      LANGUAGE_MAP: "{\"en\":\"English\",\"english\":\"English\",\"eng\":\"English\",\"sync\":\"English\"}" #Replace with your own keywords
      SYNC_KEYWORDS: "[\"sync\", \"out of sync\", \"messed up\", \"synchronization\"]" #Replace with your own keywords
```

Looks to be working now with the develop tag, thanks!
